server:
  port: 32465

spring:
  datasource:
    username: XXXX
    password: XXXX
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  redis:
    port: 6379
    host: localhost
logging:
  level:
    com.project: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
tencent:
  sms:
    secret-id: "XXXXXXXXXXXXXXXXXXX"
    secret-key: "XXXXXXXXXXXXXXXXXXX"
    sdk-app-id: XXXXXXXXXXXXXXXXXXX
    sign-name: "XXXXXXXXXXXXXXXXXXX"
    # 模板ID映射，key任意设置，value为审核通过模板ID
    template-id-map:
      register: "XXXXXXXXXXXXXXXXXXX"
      forget: "XXXXXXXXXXXXXXXXXXX"
